///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace FirstT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case2 recording.
    /// </summary>
    [TestModule("7652d8ec-41e0-4f68-b5f9-28cfbabbecb1", ModuleType.Recording, 1)]
    public partial class Case2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskRonwellRepo repository.
        /// </summary>
        public static TaskRonwellRepo repo = TaskRonwellRepo.Instance;

        static Case2 instance = new Case2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case2()
        {
            NewVariable = "null";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("9e381124-715d-410d-99a6-b58773c6dec7")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Trendyol Website launched..
            Report.Log(ReportLevel.Info, "Website", "Trendyol Website launched..\r\nOpening web site 'https://www.trendyol.com' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.trendyol.com", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            // Click Login button.
            Report.Log(ReportLevel.Info, "Mouse", "Click Login button.\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.AccountUserLink' at 52;28.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.AccountUserLinkInfo, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.AccountUserLink.Click("52;28");
            Delay.Milliseconds(0);
            
            // Click Sign up button.
            Report.Log(ReportLevel.Info, "Mouse", "Click Sign up button.\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.btnLogin' at 151;32.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.btnLoginInfo, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.btnLogin.Click("151;32");
            Delay.Milliseconds(0);
            
            // I clicked the field the enter email.
            Report.Log(ReportLevel.Info, "Mouse", "I clicked the field the enter email.\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail' at 127;31.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmailInfo, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail.Click("127;31");
            Delay.Milliseconds(0);
            
            // Sendkeys email address.
            Report.Log(ReportLevel.Info, "Keyboard", "Sendkeys email address.\r\nKey sequence 'testtask@ronwelldigital.com' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmailInfo, new RecordItemIndex(4));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterEmail.PressKeys("testtask@ronwelldigital.com");
            Delay.Milliseconds(0);
            
            // I clicked the field the enter password
            Report.Log(ReportLevel.Info, "Mouse", "I clicked the field the enter password\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput' at 125;14.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInputInfo, new RecordItemIndex(5));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput.Click("125;14");
            Delay.Milliseconds(0);
            
            // Sendkeys password.
            Report.Log(ReportLevel.Info, "Keyboard", "Sendkeys password.\r\nKey sequence 'test.123' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInputInfo, new RecordItemIndex(6));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.RegisterPasswordInput.PressKeys("test.123");
            Delay.Milliseconds(0);
            
            // I checked if password is equal.
            Report.Log(ReportLevel.Info, "Mouse", "I checked if password is equal.\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.IEyeClose' at 14;23.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.IEyeCloseInfo, new RecordItemIndex(7));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.IEyeClose.Click("14;23");
            Delay.Milliseconds(0);
            
            // Click Gender.
            Report.Log(ReportLevel.Info, "Mouse", "Click Gender.\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.MaleQButtonQButtonMediumQFluidQ' at 56;17.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.MaleQButtonQButtonMediumQFluidQInfo, new RecordItemIndex(8));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.MaleQButtonQButtonMediumQFluidQ.Click("56;17");
            Delay.Milliseconds(0);
            
            // Accept button.
            Report.Log(ReportLevel.Info, "Mouse", "Accept button.\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima' at 197;12.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(9));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima.Click("197;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima' at 15;158.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(10));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima.MoveTo("15;158");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.TyCheck' at 9;-55.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.TyCheckInfo, new RecordItemIndex(11));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.TyCheck.Click("9;-55");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.TyCheck1' at 60;-72.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.TyCheck1Info, new RecordItemIndex(12));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.TyCheck1.Click("60;-72");
            Delay.Milliseconds(0);
            
            // this is how I checked that I entered all the data correctly.
            Report.Log(ReportLevel.Info, "Mouse", "this is how I checked that I entered all the data correctly.\r\nMouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.EPOSTADOĞRULAMA' at 15;23.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.EPOSTADOĞRULAMAInfo, new RecordItemIndex(13));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.EPOSTADOĞRULAMA.Click("15;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.EPOSTADOĞRULAMA' at 332;-99.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.EPOSTADOĞRULAMAInfo, new RecordItemIndex(14));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LrContainer.EPOSTADOĞRULAMA.Click("332;-99");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
