///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FirstT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TaskRonwellRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f6b6ea51-1964-4170-866f-3e59844bbb33")]
    public partial class TaskRonwellRepo : RepoGenBaseFolder
    {
        static TaskRonwellRepo instance = new TaskRonwellRepo();
        TaskRonwellRepoFolders.ApplicationUnderTestAppFolder _applicationundertest;
        TaskRonwellRepoFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;
        TaskRonwellRepoFolders.HttpsWwwTrendyolComGiriscbEqhttpsPAppFolder _httpswwwtrendyolcomgiriscbeqhttpsp;
        TaskRonwellRepoFolders.ExplorerAppFolder _explorer;
        TaskRonwellRepoFolders.Explorer1AppFolder _explorer1;
        TaskRonwellRepoFolders.RonwellDigitalInformationTechnologyAppFolder _ronwelldigitalinformationtechnology;
        TaskRonwellRepoFolders.ChromeAppFolder _chrome;

        /// <summary>
        /// Gets the singleton class instance representing the TaskRonwellRepo element repository.
        /// </summary>
        [RepositoryFolder("f6b6ea51-1964-4170-866f-3e59844bbb33")]
        public static TaskRonwellRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TaskRonwellRepo() 
            : base("TaskRonwellRepo", "/", null, 0, false, "f6b6ea51-1964-4170-866f-3e59844bbb33", ".\\RepositoryImages\\TaskRonwellRepof6b6ea51.rximgres")
        {
            _applicationundertest = new TaskRonwellRepoFolders.ApplicationUnderTestAppFolder(this);
            _entrendueruenlertuerkiyeninonlineal = new TaskRonwellRepoFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
            _httpswwwtrendyolcomgiriscbeqhttpsp = new TaskRonwellRepoFolders.HttpsWwwTrendyolComGiriscbEqhttpsPAppFolder(this);
            _explorer = new TaskRonwellRepoFolders.ExplorerAppFolder(this);
            _explorer1 = new TaskRonwellRepoFolders.Explorer1AppFolder(this);
            _ronwelldigitalinformationtechnology = new TaskRonwellRepoFolders.RonwellDigitalInformationTechnologyAppFolder(this);
            _chrome = new TaskRonwellRepoFolders.ChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f6b6ea51-1964-4170-866f-3e59844bbb33")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("42729dbb-8f40-498b-a59b-8db7d6685549")]
        public virtual TaskRonwellRepoFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("f56b602b-e2c4-42d9-bc7e-b50287bab3bc")]
        public virtual TaskRonwellRepoFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComGiriscbEqhttpsP folder.
        /// </summary>
        [RepositoryFolder("efc835dd-d31e-4279-b981-741ac2bbe12c")]
        public virtual TaskRonwellRepoFolders.HttpsWwwTrendyolComGiriscbEqhttpsPAppFolder HttpsWwwTrendyolComGiriscbEqhttpsP
        {
            get { return _httpswwwtrendyolcomgiriscbeqhttpsp; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("83687ecd-c6c8-4792-a464-db3d85bee6c3")]
        public virtual TaskRonwellRepoFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("2648450c-8880-4e18-ba47-bab72973bdd0")]
        public virtual TaskRonwellRepoFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The RonwellDigitalInformationTechnology folder.
        /// </summary>
        [RepositoryFolder("949e2635-0951-4c19-9a3c-596e38470d88")]
        public virtual TaskRonwellRepoFolders.RonwellDigitalInformationTechnologyAppFolder RonwellDigitalInformationTechnology
        {
            get { return _ronwelldigitalinformationtechnology; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("eac807dd-0d5f-455d-9390-a5c7d0b49897")]
        public virtual TaskRonwellRepoFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TaskRonwellRepoFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("42729dbb-8f40-498b-a59b-8db7d6685549")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "42729dbb-8f40-498b-a59b-8db7d6685549", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42729dbb-8f40-498b-a59b-8db7d6685549")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42729dbb-8f40-498b-a59b-8db7d6685549")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("f56b602b-e2c4-42d9-bc7e-b50287bab3bc")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            TaskRonwellRepoFolders.HttpsWwwTrendyolComUyelikcbEqhttps1Folder _httpswwwtrendyolcomuyelikcbeqhttps1;
            TaskRonwellRepoFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder _httpswwwtrendyolcomuyelikcbeqhttps;
            TaskRonwellRepoFolders.LrContainerFolder _lrcontainer;
            RepoItemInfo _accountuserlinkInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _btnregisterInfo;
            RepoItemInfo _iuserorangeInfo;
            RepoItemInfo _imageoverlaybodyInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _sepeteeklendiInfo;
            RepoItemInfo _basketpreviewcontainervisibleInfo;
            RepoItemInfo _psumtotalInfo;
            RepoItemInfo _imageoverlaybody1Info;
            RepoItemInfo _httpswwwtrendyolcomsepetInfo;
            RepoItemInfo _sepetim4ueruenInfo;
            RepoItemInfo _imageoverlaybody2Info;
            RepoItemInfo _iarrowrightrightInfo;
            RepoItemInfo _addtobasketInfo;
            RepoItemInfo _adet2Info;
            RepoItemInfo _fvrtbtnInfo;
            RepoItemInfo _fvrtbtn1Info;
            RepoItemInfo _favorilerimInfo;
            RepoItemInfo _fvrtbtn2Info;
            RepoItemInfo _fvrtbtn3Info;
            RepoItemInfo _tuemfavorilerInfo;
            RepoItemInfo _fvrtbtn4Info;
            RepoItemInfo _headerInfo;
            RepoItemInfo _favorilerim1Info;
            RepoItemInfo _hesabımInfo;
            RepoItemInfo _İndirimkuponlarımInfo;
            RepoItemInfo _cıkışyapInfo;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "f56b602b-e2c4-42d9-bc7e-b50287bab3bc", "")
            {
                _httpswwwtrendyolcomuyelikcbeqhttps1 = new TaskRonwellRepoFolders.HttpsWwwTrendyolComUyelikcbEqhttps1Folder(this);
                _httpswwwtrendyolcomuyelikcbeqhttps = new TaskRonwellRepoFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder(this);
                _lrcontainer = new TaskRonwellRepoFolders.LrContainerFolder(this);
                _accountuserlinkInfo = new RepoItemInfo(this, "AccountUserLink", ".//div[#'account-navigation-container']/div/div[1]/div[1]", ".//div[#'account-navigation-container']/div/div[1]/div[1]", 30000, null, "ce6c6150-0be2-47e0-8c83-3f4ad39cfadb");
                _btnloginInfo = new RepoItemInfo(this, "btnLogin", ".//div[#'login-register']/div[2]/div/button[2]", ".//div[#'login-register']/div[2]/div/button[2]", 30000, null, "5f64393c-1f0b-4880-9b8c-67c664fb333c");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "370abe95-45c4-4b46-ba84-883d2b1e66ed");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "bd23f910-3fa6-4e07-bd65-7868e72e9822");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "e6d6784d-6d95-4f10-8df4-34b841503f1f");
                _btnregisterInfo = new RepoItemInfo(this, "btnRegister", ".//div[#'login-register']/div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//div[#'login-register']//span[@innertext='Üye Ol']", 30000, null, "b0dab15a-45a4-4290-a725-858537f8169b");
                _iuserorangeInfo = new RepoItemInfo(this, "IUserOrange", ".//div[#'account-navigation-container']/div/div[1]/div[1]/div/i[2]", ".//div[#'account-navigation-container']/div/div[1]/div[1]/div/i[2]", 30000, null, "da88ad99-22b2-4986-8401-bd60b78c683b");
                _imageoverlaybodyInfo = new RepoItemInfo(this, "ImageOverlayBody", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[1]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[1]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "52c7e49f-3e37-4624-afea-396e9d339f55");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//main[#'product-detail-app']/div/div[2]//button/div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "a452f266-5121-4aa0-a612-565c74f5fafb");
                _sepeteeklendiInfo = new RepoItemInfo(this, "SepeteEklendi", ".//main[#'product-detail-app']/div/div[2]//button/div[@innertext='Sepete Eklendi']", ".//main[#'product-detail-app']//div[@innertext='Sepete Eklendi']", 30000, null, "530aacdf-9f56-4ccc-9972-9c8417e0acb1");
                _basketpreviewcontainervisibleInfo = new RepoItemInfo(this, "BasketPreviewContainerVisible", ".//div[#'account-navigation-container']/div/div[2]/div", ".//div[#'account-navigation-container']/div/div[2]/div", 30000, null, "5b3f4cdf-6ec4-4005-b88e-e1de7f438d37");
                _psumtotalInfo = new RepoItemInfo(this, "PSumTotal", ".//div[#'p-layout']/aside/div/div[2]/p[2]", ".//div[#'p-layout']/aside/div/div[2]/p[2]", 30000, null, "18d8f48b-6e8b-43d5-9628-bd2f1ad78485");
                _imageoverlaybody1Info = new RepoItemInfo(this, "ImageOverlayBody1", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[3]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[3]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "6bfba02e-a0e9-4d48-901d-9eb3e546955f");
                _httpswwwtrendyolcomsepetInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComSepet", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']", 30000, null, "c9ec0785-7595-41d8-b5cb-0181cb6ab582");
                _sepetim4ueruenInfo = new RepoItemInfo(this, "Sepetim4UEruen", ".//div[#'pb-container']//div[@innertext='Sepetim (4 Ürün)']", ".//div[#'pb-container']//div[@innertext='Sepetim (4 Ürün)']", 30000, null, "8c9eb223-31e6-4600-991e-ff94f67c2d34");
                _imageoverlaybody2Info = new RepoItemInfo(this, "ImageOverlayBody2", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[2]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[2]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "9a90fa59-af75-4455-8813-930b40588d56");
                _iarrowrightrightInfo = new RepoItemInfo(this, "IArrowRightRight", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[1]/div/div[1]/i[1]", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[1]/div/div[1]/i[1]", 30000, null, "7ac7b397-5c3c-4969-b8bf-88944a3c10d7");
                _addtobasketInfo = new RepoItemInfo(this, "AddToBasket", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[6]/button", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[6]/button", 30000, null, "2c668d8a-5048-4e84-b817-7e02fa550cc1");
                _adet2Info = new RepoItemInfo(this, "Adet2", ".//div[#'account-navigation-container']/div/div[2]//ul/?/?/a[@href>'https://www.trendyol.com/']/div/p[2]/span[@innertext='Adet:2']", ".//div[#'account-navigation-container']//span[@innertext='Adet:2']", 30000, null, "f7406b1d-fa09-4ede-9b2d-dbc1d1050b71");
                _fvrtbtnInfo = new RepoItemInfo(this, "FvrtBtn", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[3]/?/?/i", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[3]/div[2]/i", 30000, null, "5f828120-0b05-469c-8f36-993c3a7abbdf");
                _fvrtbtn1Info = new RepoItemInfo(this, "FvrtBtn1", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[6]/?/?/i", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[6]/div[2]/i", 30000, null, "a3350969-44b8-4b36-a4ab-c2bef2692bec");
                _favorilerimInfo = new RepoItemInfo(this, "Favorilerim", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "35c0a3a1-1829-4e77-8cfc-5cf294989bf9");
                _fvrtbtn2Info = new RepoItemInfo(this, "FvrtBtn2", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[2]/div[2]/i", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[2]/div[2]/i", 30000, null, "eb965194-7060-492c-95d3-9eb2126f9a9b");
                _fvrtbtn3Info = new RepoItemInfo(this, "FvrtBtn3", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[11]/?/?/i", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[11]/div[2]/i", 30000, null, "f402591c-296f-4637-a754-e0ff7e31c716");
                _tuemfavorilerInfo = new RepoItemInfo(this, "TuemFavoriler", ".//div[#'account-gw-favorites']/div/div[2]//span[@innertext='Tüm Favoriler']", ".//div[#'account-gw-favorites']//span[@innertext='Tüm Favoriler']", 30000, null, "ab269eee-1d41-495f-8a21-da5c9958d52c");
                _fvrtbtn4Info = new RepoItemInfo(this, "FvrtBtn4", ".//div[#'search-app']/div/div[1]/div[2]/div[3]/div/div[1]/?/?/i", ".//div[#'search-app']//i", 30000, null, "5d98e63b-6f9c-4cb8-b33f-b62ed8e5244e");
                _headerInfo = new RepoItemInfo(this, "Header", ".//div[#'sticky-header']/div/div", ".//div[#'sticky-header']/div/div", 30000, null, "6f711799-4ded-434d-aed4-62a935fb67b6");
                _favorilerim1Info = new RepoItemInfo(this, "Favorilerim1", ".//div[#'account-gw-favorites']/div/div[1]/div/div[1]/a[1]/span[@innertext='Favorilerim']", ".//div[#'account-gw-favorites']//span[@innertext='Favorilerim']", 30000, null, "7d23d51f-b3c0-4be0-be2d-ddda3f595d5a");
                _hesabımInfo = new RepoItemInfo(this, "Hesabım", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Hesabım']", ".//div[#'account-navigation-container']//p[@innertext='Hesabım']", 30000, null, "e2c53df6-fa3f-422e-9e20-40630779a797");
                _İndirimkuponlarımInfo = new RepoItemInfo(this, "İndirimKuponlarım", ".//div[#'account-navigation-container']/div/div[1]/div[2]/div/a[5]/p[@innertext='İndirim Kuponlarım']", ".//div[#'account-navigation-container']//p[@innertext='İndirim Kuponlarım']", 30000, null, "0c251df4-dd25-46f1-887f-9cdbc68b7895");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", ".//div[#'account-navigation-container']/div/div[1]/div[2]/div/a[9]/p[@innertext='Çıkış Yap']", ".//div[#'account-navigation-container']//p[@innertext='Çıkış Yap']", 30000, null, "5613b175-c9aa-4e66-b7d6-6a14cce31ac4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f56b602b-e2c4-42d9-bc7e-b50287bab3bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f56b602b-e2c4-42d9-bc7e-b50287bab3bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AccountUserLink item.
            /// </summary>
            [RepositoryItem("ce6c6150-0be2-47e0-8c83-3f4ad39cfadb")]
            public virtual Ranorex.DivTag AccountUserLink
            {
                get
                {
                    return _accountuserlinkInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AccountUserLink item info.
            /// </summary>
            [RepositoryItemInfo("ce6c6150-0be2-47e0-8c83-3f4ad39cfadb")]
            public virtual RepoItemInfo AccountUserLinkInfo
            {
                get
                {
                    return _accountuserlinkInfo;
                }
            }

            /// <summary>
            /// The btnLogin item.
            /// </summary>
            [RepositoryItem("5f64393c-1f0b-4880-9b8c-67c664fb333c")]
            public virtual Ranorex.ButtonTag btnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The btnLogin item info.
            /// </summary>
            [RepositoryItemInfo("5f64393c-1f0b-4880-9b8c-67c664fb333c")]
            public virtual RepoItemInfo btnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("370abe95-45c4-4b46-ba84-883d2b1e66ed")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("370abe95-45c4-4b46-ba84-883d2b1e66ed")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("bd23f910-3fa6-4e07-bd65-7868e72e9822")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("bd23f910-3fa6-4e07-bd65-7868e72e9822")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("e6d6784d-6d95-4f10-8df4-34b841503f1f")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("e6d6784d-6d95-4f10-8df4-34b841503f1f")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The btnRegister item.
            /// </summary>
            [RepositoryItem("b0dab15a-45a4-4290-a725-858537f8169b")]
            public virtual Ranorex.SpanTag btnRegister
            {
                get
                {
                    return _btnregisterInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The btnRegister item info.
            /// </summary>
            [RepositoryItemInfo("b0dab15a-45a4-4290-a725-858537f8169b")]
            public virtual RepoItemInfo btnRegisterInfo
            {
                get
                {
                    return _btnregisterInfo;
                }
            }

            /// <summary>
            /// The IUserOrange item.
            /// </summary>
            [RepositoryItem("da88ad99-22b2-4986-8401-bd60b78c683b")]
            public virtual Ranorex.ITag IUserOrange
            {
                get
                {
                    return _iuserorangeInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IUserOrange item info.
            /// </summary>
            [RepositoryItemInfo("da88ad99-22b2-4986-8401-bd60b78c683b")]
            public virtual RepoItemInfo IUserOrangeInfo
            {
                get
                {
                    return _iuserorangeInfo;
                }
            }

            /// <summary>
            /// The ImageOverlayBody item.
            /// </summary>
            [RepositoryItem("52c7e49f-3e37-4624-afea-396e9d339f55")]
            public virtual Ranorex.DivTag ImageOverlayBody
            {
                get
                {
                    return _imageoverlaybodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody item info.
            /// </summary>
            [RepositoryItemInfo("52c7e49f-3e37-4624-afea-396e9d339f55")]
            public virtual RepoItemInfo ImageOverlayBodyInfo
            {
                get
                {
                    return _imageoverlaybodyInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("a452f266-5121-4aa0-a612-565c74f5fafb")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("a452f266-5121-4aa0-a612-565c74f5fafb")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The SepeteEklendi item.
            /// </summary>
            [RepositoryItem("530aacdf-9f56-4ccc-9972-9c8417e0acb1")]
            public virtual Ranorex.DivTag SepeteEklendi
            {
                get
                {
                    return _sepeteeklendiInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEklendi item info.
            /// </summary>
            [RepositoryItemInfo("530aacdf-9f56-4ccc-9972-9c8417e0acb1")]
            public virtual RepoItemInfo SepeteEklendiInfo
            {
                get
                {
                    return _sepeteeklendiInfo;
                }
            }

            /// <summary>
            /// The BasketPreviewContainerVisible item.
            /// </summary>
            [RepositoryItem("5b3f4cdf-6ec4-4005-b88e-e1de7f438d37")]
            public virtual Ranorex.DivTag BasketPreviewContainerVisible
            {
                get
                {
                    return _basketpreviewcontainervisibleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BasketPreviewContainerVisible item info.
            /// </summary>
            [RepositoryItemInfo("5b3f4cdf-6ec4-4005-b88e-e1de7f438d37")]
            public virtual RepoItemInfo BasketPreviewContainerVisibleInfo
            {
                get
                {
                    return _basketpreviewcontainervisibleInfo;
                }
            }

            /// <summary>
            /// The PSumTotal item.
            /// </summary>
            [RepositoryItem("18d8f48b-6e8b-43d5-9628-bd2f1ad78485")]
            public virtual Ranorex.PTag PSumTotal
            {
                get
                {
                    return _psumtotalInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PSumTotal item info.
            /// </summary>
            [RepositoryItemInfo("18d8f48b-6e8b-43d5-9628-bd2f1ad78485")]
            public virtual RepoItemInfo PSumTotalInfo
            {
                get
                {
                    return _psumtotalInfo;
                }
            }

            /// <summary>
            /// The ImageOverlayBody1 item.
            /// </summary>
            [RepositoryItem("6bfba02e-a0e9-4d48-901d-9eb3e546955f")]
            public virtual Ranorex.DivTag ImageOverlayBody1
            {
                get
                {
                    return _imageoverlaybody1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody1 item info.
            /// </summary>
            [RepositoryItemInfo("6bfba02e-a0e9-4d48-901d-9eb3e546955f")]
            public virtual RepoItemInfo ImageOverlayBody1Info
            {
                get
                {
                    return _imageoverlaybody1Info;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepet item.
            /// </summary>
            [RepositoryItem("c9ec0785-7595-41d8-b5cb-0181cb6ab582")]
            public virtual Ranorex.ATag HttpsWwwTrendyolComSepet
            {
                get
                {
                    return _httpswwwtrendyolcomsepetInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComSepet item info.
            /// </summary>
            [RepositoryItemInfo("c9ec0785-7595-41d8-b5cb-0181cb6ab582")]
            public virtual RepoItemInfo HttpsWwwTrendyolComSepetInfo
            {
                get
                {
                    return _httpswwwtrendyolcomsepetInfo;
                }
            }

            /// <summary>
            /// The Sepetim4UEruen item.
            /// </summary>
            [RepositoryItem("8c9eb223-31e6-4600-991e-ff94f67c2d34")]
            public virtual Ranorex.DivTag Sepetim4UEruen
            {
                get
                {
                    return _sepetim4ueruenInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim4UEruen item info.
            /// </summary>
            [RepositoryItemInfo("8c9eb223-31e6-4600-991e-ff94f67c2d34")]
            public virtual RepoItemInfo Sepetim4UEruenInfo
            {
                get
                {
                    return _sepetim4ueruenInfo;
                }
            }

            /// <summary>
            /// The ImageOverlayBody2 item.
            /// </summary>
            [RepositoryItem("9a90fa59-af75-4455-8813-930b40588d56")]
            public virtual Ranorex.DivTag ImageOverlayBody2
            {
                get
                {
                    return _imageoverlaybody2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody2 item info.
            /// </summary>
            [RepositoryItemInfo("9a90fa59-af75-4455-8813-930b40588d56")]
            public virtual RepoItemInfo ImageOverlayBody2Info
            {
                get
                {
                    return _imageoverlaybody2Info;
                }
            }

            /// <summary>
            /// The IArrowRightRight item.
            /// </summary>
            [RepositoryItem("7ac7b397-5c3c-4969-b8bf-88944a3c10d7")]
            public virtual Ranorex.ITag IArrowRightRight
            {
                get
                {
                    return _iarrowrightrightInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IArrowRightRight item info.
            /// </summary>
            [RepositoryItemInfo("7ac7b397-5c3c-4969-b8bf-88944a3c10d7")]
            public virtual RepoItemInfo IArrowRightRightInfo
            {
                get
                {
                    return _iarrowrightrightInfo;
                }
            }

            /// <summary>
            /// The AddToBasket item.
            /// </summary>
            [RepositoryItem("2c668d8a-5048-4e84-b817-7e02fa550cc1")]
            public virtual Ranorex.ButtonTag AddToBasket
            {
                get
                {
                    return _addtobasketInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToBasket item info.
            /// </summary>
            [RepositoryItemInfo("2c668d8a-5048-4e84-b817-7e02fa550cc1")]
            public virtual RepoItemInfo AddToBasketInfo
            {
                get
                {
                    return _addtobasketInfo;
                }
            }

            /// <summary>
            /// The Adet2 item.
            /// </summary>
            [RepositoryItem("f7406b1d-fa09-4ede-9b2d-dbc1d1050b71")]
            public virtual Ranorex.SpanTag Adet2
            {
                get
                {
                    return _adet2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Adet2 item info.
            /// </summary>
            [RepositoryItemInfo("f7406b1d-fa09-4ede-9b2d-dbc1d1050b71")]
            public virtual RepoItemInfo Adet2Info
            {
                get
                {
                    return _adet2Info;
                }
            }

            /// <summary>
            /// The FvrtBtn item.
            /// </summary>
            [RepositoryItem("5f828120-0b05-469c-8f36-993c3a7abbdf")]
            public virtual Ranorex.ITag FvrtBtn
            {
                get
                {
                    return _fvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("5f828120-0b05-469c-8f36-993c3a7abbdf")]
            public virtual RepoItemInfo FvrtBtnInfo
            {
                get
                {
                    return _fvrtbtnInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn1 item.
            /// </summary>
            [RepositoryItem("a3350969-44b8-4b36-a4ab-c2bef2692bec")]
            public virtual Ranorex.ITag FvrtBtn1
            {
                get
                {
                    return _fvrtbtn1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn1 item info.
            /// </summary>
            [RepositoryItemInfo("a3350969-44b8-4b36-a4ab-c2bef2692bec")]
            public virtual RepoItemInfo FvrtBtn1Info
            {
                get
                {
                    return _fvrtbtn1Info;
                }
            }

            /// <summary>
            /// The Favorilerim item.
            /// </summary>
            [RepositoryItem("35c0a3a1-1829-4e77-8cfc-5cf294989bf9")]
            public virtual Ranorex.PTag Favorilerim
            {
                get
                {
                    return _favorilerimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Favorilerim item info.
            /// </summary>
            [RepositoryItemInfo("35c0a3a1-1829-4e77-8cfc-5cf294989bf9")]
            public virtual RepoItemInfo FavorilerimInfo
            {
                get
                {
                    return _favorilerimInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn2 item.
            /// </summary>
            [RepositoryItem("eb965194-7060-492c-95d3-9eb2126f9a9b")]
            public virtual Ranorex.ITag FvrtBtn2
            {
                get
                {
                    return _fvrtbtn2Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn2 item info.
            /// </summary>
            [RepositoryItemInfo("eb965194-7060-492c-95d3-9eb2126f9a9b")]
            public virtual RepoItemInfo FvrtBtn2Info
            {
                get
                {
                    return _fvrtbtn2Info;
                }
            }

            /// <summary>
            /// The FvrtBtn3 item.
            /// </summary>
            [RepositoryItem("f402591c-296f-4637-a754-e0ff7e31c716")]
            public virtual Ranorex.ITag FvrtBtn3
            {
                get
                {
                    return _fvrtbtn3Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn3 item info.
            /// </summary>
            [RepositoryItemInfo("f402591c-296f-4637-a754-e0ff7e31c716")]
            public virtual RepoItemInfo FvrtBtn3Info
            {
                get
                {
                    return _fvrtbtn3Info;
                }
            }

            /// <summary>
            /// The TuemFavoriler item.
            /// </summary>
            [RepositoryItem("ab269eee-1d41-495f-8a21-da5c9958d52c")]
            public virtual Ranorex.SpanTag TuemFavoriler
            {
                get
                {
                    return _tuemfavorilerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TuemFavoriler item info.
            /// </summary>
            [RepositoryItemInfo("ab269eee-1d41-495f-8a21-da5c9958d52c")]
            public virtual RepoItemInfo TuemFavorilerInfo
            {
                get
                {
                    return _tuemfavorilerInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn4 item.
            /// </summary>
            [RepositoryItem("5d98e63b-6f9c-4cb8-b33f-b62ed8e5244e")]
            public virtual Ranorex.ITag FvrtBtn4
            {
                get
                {
                    return _fvrtbtn4Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn4 item info.
            /// </summary>
            [RepositoryItemInfo("5d98e63b-6f9c-4cb8-b33f-b62ed8e5244e")]
            public virtual RepoItemInfo FvrtBtn4Info
            {
                get
                {
                    return _fvrtbtn4Info;
                }
            }

            /// <summary>
            /// The Header item.
            /// </summary>
            [RepositoryItem("6f711799-4ded-434d-aed4-62a935fb67b6")]
            public virtual Ranorex.DivTag Header
            {
                get
                {
                    return _headerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Header item info.
            /// </summary>
            [RepositoryItemInfo("6f711799-4ded-434d-aed4-62a935fb67b6")]
            public virtual RepoItemInfo HeaderInfo
            {
                get
                {
                    return _headerInfo;
                }
            }

            /// <summary>
            /// The Favorilerim1 item.
            /// </summary>
            [RepositoryItem("7d23d51f-b3c0-4be0-be2d-ddda3f595d5a")]
            public virtual Ranorex.SpanTag Favorilerim1
            {
                get
                {
                    return _favorilerim1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Favorilerim1 item info.
            /// </summary>
            [RepositoryItemInfo("7d23d51f-b3c0-4be0-be2d-ddda3f595d5a")]
            public virtual RepoItemInfo Favorilerim1Info
            {
                get
                {
                    return _favorilerim1Info;
                }
            }

            /// <summary>
            /// The Hesabım item.
            /// </summary>
            [RepositoryItem("e2c53df6-fa3f-422e-9e20-40630779a797")]
            public virtual Ranorex.PTag Hesabım
            {
                get
                {
                    return _hesabımInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Hesabım item info.
            /// </summary>
            [RepositoryItemInfo("e2c53df6-fa3f-422e-9e20-40630779a797")]
            public virtual RepoItemInfo HesabımInfo
            {
                get
                {
                    return _hesabımInfo;
                }
            }

            /// <summary>
            /// The İndirimKuponlarım item.
            /// </summary>
            [RepositoryItem("0c251df4-dd25-46f1-887f-9cdbc68b7895")]
            public virtual Ranorex.PTag İndirimKuponlarım
            {
                get
                {
                    return _İndirimkuponlarımInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The İndirimKuponlarım item info.
            /// </summary>
            [RepositoryItemInfo("0c251df4-dd25-46f1-887f-9cdbc68b7895")]
            public virtual RepoItemInfo İndirimKuponlarımInfo
            {
                get
                {
                    return _İndirimkuponlarımInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("5613b175-c9aa-4e66-b7d6-6a14cce31ac4")]
            public virtual Ranorex.PTag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("5613b175-c9aa-4e66-b7d6-6a14cce31ac4")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComUyelikcbEqhttps1 folder.
            /// </summary>
            [RepositoryFolder("4e872118-9868-4ad3-803e-2fb0971b05d3")]
            public virtual TaskRonwellRepoFolders.HttpsWwwTrendyolComUyelikcbEqhttps1Folder HttpsWwwTrendyolComUyelikcbEqhttps1
            {
                get { return _httpswwwtrendyolcomuyelikcbeqhttps1; }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComUyelikcbEqhttps folder.
            /// </summary>
            [RepositoryFolder("9decf6ec-c897-4578-a71e-e7253d61deea")]
            public virtual TaskRonwellRepoFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder HttpsWwwTrendyolComUyelikcbEqhttps
            {
                get { return _httpswwwtrendyolcomuyelikcbeqhttps; }
            }

            /// <summary>
            /// The LrContainer folder.
            /// </summary>
            [RepositoryFolder("efb3c3f8-d2b0-46ab-8837-6224f75182c7")]
            public virtual TaskRonwellRepoFolders.LrContainerFolder LrContainer
            {
                get { return _lrcontainer; }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttps1Folder folder.
        /// </summary>
        [RepositoryFolder("4e872118-9868-4ad3-803e-2fb0971b05d3")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttps1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _httpswwwtrendyolcomuyelikcbeqhttpsInfo;
            RepoItemInfo _emailinputqinputwrapperInfo;
            RepoItemInfo _ieyecloseInfo;
            RepoItemInfo _maleqbuttonqbuttonmediumqfluidqInfo;
            RepoItemInfo _tycheckboxwrappertydisplayflexInfo;
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _ueyeolInfo;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps1  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttps1Folder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps1", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']", parentFolder, 30000, null, false, "4e872118-9868-4ad3-803e-2fb0971b05d3", "")
            {
                _httpswwwtrendyolcomuyelikcbeqhttpsInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComUyelikcbEqhttps", "", "", 30000, null, "3b05da99-3a57-48e3-999f-5ee7f69d5490");
                _emailinputqinputwrapperInfo = new RepoItemInfo(this, "EmailInputQInputWrapper", "div[1]", "div[1]", 30000, null, "4378bb58-f50b-4484-921c-7a423ab91dcc");
                _ieyecloseInfo = new RepoItemInfo(this, "IEyeClose", "div[2]/?/?/i", "div[2]/div/i", 30000, null, "e5a701c6-c186-4eab-a7ff-b3894f28d0e9");
                _maleqbuttonqbuttonmediumqfluidqInfo = new RepoItemInfo(this, "MaleQButtonQButtonMediumQFluidQ", "div[3]/div/button[2]", "div[3]/div/button[2]", 30000, null, "e6c5810f-ada7-4a21-93db-adcbed65e26f");
                _tycheckboxwrappertydisplayflexInfo = new RepoItemInfo(this, "TyCheckboxWrapperTyDisplayFlex", "div[5]/div/div[1]", "div[5]/div/div[1]", 30000, null, "6aaeafaa-c2cb-459e-891b-e65e2b1cfd12");
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", "button", "button", 30000, null, "37cf6617-2557-4cc8-b5f8-99182a5cc3df");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", "?/?/span[@innertext='Üye Ol']", "button/span[@innertext='Üye Ol']", 30000, null, "b621eb08-8c4c-4279-9831-bb2d86e921e7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4e872118-9868-4ad3-803e-2fb0971b05d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4e872118-9868-4ad3-803e-2fb0971b05d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComUyelikcbEqhttps item.
            /// </summary>
            [RepositoryItem("3b05da99-3a57-48e3-999f-5ee7f69d5490")]
            public virtual Ranorex.FormTag HttpsWwwTrendyolComUyelikcbEqhttps
            {
                get
                {
                    return _httpswwwtrendyolcomuyelikcbeqhttpsInfo.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComUyelikcbEqhttps item info.
            /// </summary>
            [RepositoryItemInfo("3b05da99-3a57-48e3-999f-5ee7f69d5490")]
            public virtual RepoItemInfo HttpsWwwTrendyolComUyelikcbEqhttpsInfo
            {
                get
                {
                    return _httpswwwtrendyolcomuyelikcbeqhttpsInfo;
                }
            }

            /// <summary>
            /// The EmailInputQInputWrapper item.
            /// </summary>
            [RepositoryItem("4378bb58-f50b-4484-921c-7a423ab91dcc")]
            public virtual Ranorex.DivTag EmailInputQInputWrapper
            {
                get
                {
                    return _emailinputqinputwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EmailInputQInputWrapper item info.
            /// </summary>
            [RepositoryItemInfo("4378bb58-f50b-4484-921c-7a423ab91dcc")]
            public virtual RepoItemInfo EmailInputQInputWrapperInfo
            {
                get
                {
                    return _emailinputqinputwrapperInfo;
                }
            }

            /// <summary>
            /// The IEyeClose item.
            /// </summary>
            [RepositoryItem("e5a701c6-c186-4eab-a7ff-b3894f28d0e9")]
            public virtual Ranorex.ITag IEyeClose
            {
                get
                {
                    return _ieyecloseInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IEyeClose item info.
            /// </summary>
            [RepositoryItemInfo("e5a701c6-c186-4eab-a7ff-b3894f28d0e9")]
            public virtual RepoItemInfo IEyeCloseInfo
            {
                get
                {
                    return _ieyecloseInfo;
                }
            }

            /// <summary>
            /// The MaleQButtonQButtonMediumQFluidQ item.
            /// </summary>
            [RepositoryItem("e6c5810f-ada7-4a21-93db-adcbed65e26f")]
            public virtual Ranorex.ButtonTag MaleQButtonQButtonMediumQFluidQ
            {
                get
                {
                    return _maleqbuttonqbuttonmediumqfluidqInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The MaleQButtonQButtonMediumQFluidQ item info.
            /// </summary>
            [RepositoryItemInfo("e6c5810f-ada7-4a21-93db-adcbed65e26f")]
            public virtual RepoItemInfo MaleQButtonQButtonMediumQFluidQInfo
            {
                get
                {
                    return _maleqbuttonqbuttonmediumqfluidqInfo;
                }
            }

            /// <summary>
            /// The TyCheckboxWrapperTyDisplayFlex item.
            /// </summary>
            [RepositoryItem("6aaeafaa-c2cb-459e-891b-e65e2b1cfd12")]
            public virtual Ranorex.DivTag TyCheckboxWrapperTyDisplayFlex
            {
                get
                {
                    return _tycheckboxwrappertydisplayflexInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TyCheckboxWrapperTyDisplayFlex item info.
            /// </summary>
            [RepositoryItemInfo("6aaeafaa-c2cb-459e-891b-e65e2b1cfd12")]
            public virtual RepoItemInfo TyCheckboxWrapperTyDisplayFlexInfo
            {
                get
                {
                    return _tycheckboxwrappertydisplayflexInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("37cf6617-2557-4cc8-b5f8-99182a5cc3df")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("37cf6617-2557-4cc8-b5f8-99182a5cc3df")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("b621eb08-8c4c-4279-9831-bb2d86e921e7")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("b621eb08-8c4c-4279-9831-bb2d86e921e7")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttpsFolder folder.
        /// </summary>
        [RepositoryFolder("9decf6ec-c897-4578-a71e-e7253d61deea")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttpsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _ieyecloseInfo;
            RepoItemInfo _maleqbuttonqbuttonmediumqfluidqInfo;
            RepoItemInfo _tybgbeigetyborderedtycheckboxtyiInfo;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttpsFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2Fbutik%2Fliste%2F2%2Ferkek']", parentFolder, 30000, null, false, "9decf6ec-c897-4578-a71e-e7253d61deea", "")
            {
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", "button", "button", 30000, null, "086ada77-5bb1-4270-9172-a8d2bff3b7c5");
                _ieyecloseInfo = new RepoItemInfo(this, "IEyeClose", "div[2]/?/?/i", "div[2]/div/i", 30000, null, "9df3887a-3895-4e85-8f83-564512daf048");
                _maleqbuttonqbuttonmediumqfluidqInfo = new RepoItemInfo(this, "MaleQButtonQButtonMediumQFluidQ", "div[3]/div/button[2]", "div[3]/div/button[2]", 30000, null, "1a364b9e-0088-4286-a4cd-6f8dcf1e5071");
                _tybgbeigetyborderedtycheckboxtyiInfo = new RepoItemInfo(this, "TyBgBeigeTyBorderedTyCheckboxTyI", "div[6]/div/div[1]/div/div", "div[1]/div/div", 30000, null, "13bb342e-4837-4e3f-a030-04b1fdbee42c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9decf6ec-c897-4578-a71e-e7253d61deea")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9decf6ec-c897-4578-a71e-e7253d61deea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("086ada77-5bb1-4270-9172-a8d2bff3b7c5")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("086ada77-5bb1-4270-9172-a8d2bff3b7c5")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The IEyeClose item.
            /// </summary>
            [RepositoryItem("9df3887a-3895-4e85-8f83-564512daf048")]
            public virtual Ranorex.ITag IEyeClose
            {
                get
                {
                    return _ieyecloseInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IEyeClose item info.
            /// </summary>
            [RepositoryItemInfo("9df3887a-3895-4e85-8f83-564512daf048")]
            public virtual RepoItemInfo IEyeCloseInfo
            {
                get
                {
                    return _ieyecloseInfo;
                }
            }

            /// <summary>
            /// The MaleQButtonQButtonMediumQFluidQ item.
            /// </summary>
            [RepositoryItem("1a364b9e-0088-4286-a4cd-6f8dcf1e5071")]
            public virtual Ranorex.ButtonTag MaleQButtonQButtonMediumQFluidQ
            {
                get
                {
                    return _maleqbuttonqbuttonmediumqfluidqInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The MaleQButtonQButtonMediumQFluidQ item info.
            /// </summary>
            [RepositoryItemInfo("1a364b9e-0088-4286-a4cd-6f8dcf1e5071")]
            public virtual RepoItemInfo MaleQButtonQButtonMediumQFluidQInfo
            {
                get
                {
                    return _maleqbuttonqbuttonmediumqfluidqInfo;
                }
            }

            /// <summary>
            /// The TyBgBeigeTyBorderedTyCheckboxTyI item.
            /// </summary>
            [RepositoryItem("13bb342e-4837-4e3f-a030-04b1fdbee42c")]
            public virtual Ranorex.DivTag TyBgBeigeTyBorderedTyCheckboxTyI
            {
                get
                {
                    return _tybgbeigetyborderedtycheckboxtyiInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TyBgBeigeTyBorderedTyCheckboxTyI item info.
            /// </summary>
            [RepositoryItemInfo("13bb342e-4837-4e3f-a030-04b1fdbee42c")]
            public virtual RepoItemInfo TyBgBeigeTyBorderedTyCheckboxTyIInfo
            {
                get
                {
                    return _tybgbeigetyborderedtycheckboxtyiInfo;
                }
            }
        }

        /// <summary>
        /// The LrContainerFolder folder.
        /// </summary>
        [RepositoryFolder("efb3c3f8-d2b0-46ab-8837-6224f75182c7")]
        public partial class LrContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tycheck1Info;
            RepoItemInfo _tycheckInfo;
            RepoItemInfo _epostadoğrulamaInfo;
            RepoItemInfo _trendyolagirişyapveyahesapoluşturInfo;

            /// <summary>
            /// Creates a new LrContainer  folder.
            /// </summary>
            public LrContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("LrContainer", ".//div[#'login-register']/div[3]", parentFolder, 30000, null, false, "efb3c3f8-d2b0-46ab-8837-6224f75182c7", "")
            {
                _tycheck1Info = new RepoItemInfo(this, "TyCheck1", "?/?/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2Fbutik%2Fliste%2F2%2Ferkek']/div[5]//svg", "svg", 30000, null, "de67ca81-f5d3-41f0-a613-ae422b089c91");
                _tycheckInfo = new RepoItemInfo(this, "TyCheck", "?/?/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2Fbutik%2Fliste%2F2%2Ferkek']/div[6]//svg", "form/div[6]/div/div[1]/div/svg", 30000, null, "c93409ee-55b7-4852-b23f-d7e498c7ed88");
                _epostadoğrulamaInfo = new RepoItemInfo(this, "EPOSTADOĞRULAMA", "div[1]//span[@innertext='E-POSTA DOĞRULAMA']", "span[@innertext='E-POSTA DOĞRULAMA']", 30000, null, "d0abf5ff-af22-41d3-b8f2-081675c0b4cb");
                _trendyolagirişyapveyahesapoluşturInfo = new RepoItemInfo(this, "TrendyolaGirişYapVeyaHesapOluştur", "?/?/h3[@innertext>'Trendyol’a giriş yap veya']", "?/?/h3[@innertext>'Trendyol’a giriş yap veya']", 30000, null, "1b402a06-ede0-46c7-b118-648b0c6899be");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("efb3c3f8-d2b0-46ab-8837-6224f75182c7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("efb3c3f8-d2b0-46ab-8837-6224f75182c7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TyCheck1 item.
            /// </summary>
            [RepositoryItem("de67ca81-f5d3-41f0-a613-ae422b089c91")]
            public virtual Ranorex.SvgTag TyCheck1
            {
                get
                {
                    return _tycheck1Info.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The TyCheck1 item info.
            /// </summary>
            [RepositoryItemInfo("de67ca81-f5d3-41f0-a613-ae422b089c91")]
            public virtual RepoItemInfo TyCheck1Info
            {
                get
                {
                    return _tycheck1Info;
                }
            }

            /// <summary>
            /// The TyCheck item.
            /// </summary>
            [RepositoryItem("c93409ee-55b7-4852-b23f-d7e498c7ed88")]
            public virtual Ranorex.SvgTag TyCheck
            {
                get
                {
                    return _tycheckInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The TyCheck item info.
            /// </summary>
            [RepositoryItemInfo("c93409ee-55b7-4852-b23f-d7e498c7ed88")]
            public virtual RepoItemInfo TyCheckInfo
            {
                get
                {
                    return _tycheckInfo;
                }
            }

            /// <summary>
            /// The EPOSTADOĞRULAMA item.
            /// </summary>
            [RepositoryItem("d0abf5ff-af22-41d3-b8f2-081675c0b4cb")]
            public virtual Ranorex.SpanTag EPOSTADOĞRULAMA
            {
                get
                {
                    return _epostadoğrulamaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EPOSTADOĞRULAMA item info.
            /// </summary>
            [RepositoryItemInfo("d0abf5ff-af22-41d3-b8f2-081675c0b4cb")]
            public virtual RepoItemInfo EPOSTADOĞRULAMAInfo
            {
                get
                {
                    return _epostadoğrulamaInfo;
                }
            }

            /// <summary>
            /// The TrendyolaGirişYapVeyaHesapOluştur item.
            /// </summary>
            [RepositoryItem("1b402a06-ede0-46c7-b118-648b0c6899be")]
            public virtual Ranorex.H3Tag TrendyolaGirişYapVeyaHesapOluştur
            {
                get
                {
                    return _trendyolagirişyapveyahesapoluşturInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The TrendyolaGirişYapVeyaHesapOluştur item info.
            /// </summary>
            [RepositoryItemInfo("1b402a06-ede0-46c7-b118-648b0c6899be")]
            public virtual RepoItemInfo TrendyolaGirişYapVeyaHesapOluşturInfo
            {
                get
                {
                    return _trendyolagirişyapveyahesapoluşturInfo;
                }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComGiriscbEqhttpsPAppFolder folder.
        /// </summary>
        [RepositoryFolder("efc835dd-d31e-4279-b981-741ac2bbe12c")]
        public partial class HttpsWwwTrendyolComGiriscbEqhttpsPAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element135912512Info;
            RepoItemInfo _httpswwwtrendyolcomgiriscbeqhttpspInfo;
            RepoItemInfo _kapatInfo;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComGiriscbEqhttpsP  folder.
            /// </summary>
            public HttpsWwwTrendyolComGiriscbEqhttpsPAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComGiriscbEqhttpsP", "/form[@title>'https://www.trendyol.com/']", parentFolder, 30000, null, true, "efc835dd-d31e-4279-b981-741ac2bbe12c", "")
            {
                _element135912512Info = new RepoItemInfo(this, "Element135912512", "element[@controlid='135912512']", "element[@controlid='135912512']", 30000, null, "46bed207-302e-4edc-964c-82b5e2eee087");
                _httpswwwtrendyolcomgiriscbeqhttpspInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComGiriscbEqhttpsP", "container[@accessiblename>'Google Çeviri - Google Ch']/container[@accessiblename='Google Chrome']//tabpagelist[@accessiblerole='PageTabList']/?/?/tabpage[@accessiblename>'https://www.trendyol.com/']", ".//tabpage[@accessiblename>'https://www.trendyol.com/']", 30000, null, "6455ae73-5373-4f54-9bad-9281f3ea3c13");
                _kapatInfo = new RepoItemInfo(this, "Kapat", "container[@accessiblename>'Erkek Butikleri, Yeni Sezon']/container[@accessiblename='Google Chrome']//tabpagelist[@accessiblerole='PageTabList']/?/?/tabpage[@accessiblename>'Erkek Butikleri, Yeni Sezon']/button[@accessiblename='Kapat']", ".//tabpage[@accessiblename>'Erkek Butikleri, Yeni Sezon']/button[@accessiblename='Kapat']", 30000, null, "c80654ce-59fc-460a-bb3a-6763b4cf95d1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("efc835dd-d31e-4279-b981-741ac2bbe12c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("efc835dd-d31e-4279-b981-741ac2bbe12c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element135912512 item.
            /// </summary>
            [RepositoryItem("46bed207-302e-4edc-964c-82b5e2eee087")]
            public virtual Ranorex.Unknown Element135912512
            {
                get
                {
                    return _element135912512Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element135912512 item info.
            /// </summary>
            [RepositoryItemInfo("46bed207-302e-4edc-964c-82b5e2eee087")]
            public virtual RepoItemInfo Element135912512Info
            {
                get
                {
                    return _element135912512Info;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComGiriscbEqhttpsP item.
            /// </summary>
            [RepositoryItem("6455ae73-5373-4f54-9bad-9281f3ea3c13")]
            public virtual Ranorex.TabPage HttpsWwwTrendyolComGiriscbEqhttpsP
            {
                get
                {
                    return _httpswwwtrendyolcomgiriscbeqhttpspInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComGiriscbEqhttpsP item info.
            /// </summary>
            [RepositoryItemInfo("6455ae73-5373-4f54-9bad-9281f3ea3c13")]
            public virtual RepoItemInfo HttpsWwwTrendyolComGiriscbEqhttpsPInfo
            {
                get
                {
                    return _httpswwwtrendyolcomgiriscbeqhttpspInfo;
                }
            }

            /// <summary>
            /// The Kapat item.
            /// </summary>
            [RepositoryItem("c80654ce-59fc-460a-bb3a-6763b4cf95d1")]
            public virtual Ranorex.Button Kapat
            {
                get
                {
                    return _kapatInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kapat item info.
            /// </summary>
            [RepositoryItemInfo("c80654ce-59fc-460a-bb3a-6763b4cf95d1")]
            public virtual RepoItemInfo KapatInfo
            {
                get
                {
                    return _kapatInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("83687ecd-c6c8-4792-a464-db3d85bee6c3")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechrome21calışanpencereInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "83687ecd-c6c8-4792-a464-db3d85bee6c3", "")
            {
                _googlechrome21calışanpencereInfo = new RepoItemInfo(this, "GoogleChrome21CalışanPencere", "container[@controlid='40965']//toolbar[@accessiblename='Çalışan uygulamalar']/button[14]", ".//toolbar[@accessiblename='Çalışan uygulamalar']/button[14]", 30000, null, "aea12297-fcec-4e76-88d7-4db62edf938a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83687ecd-c6c8-4792-a464-db3d85bee6c3")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83687ecd-c6c8-4792-a464-db3d85bee6c3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome21CalışanPencere item.
            /// </summary>
            [RepositoryItem("aea12297-fcec-4e76-88d7-4db62edf938a")]
            public virtual Ranorex.Button GoogleChrome21CalışanPencere
            {
                get
                {
                    return _googlechrome21calışanpencereInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome21CalışanPencere item info.
            /// </summary>
            [RepositoryItemInfo("aea12297-fcec-4e76-88d7-4db62edf938a")]
            public virtual RepoItemInfo GoogleChrome21CalışanPencereInfo
            {
                get
                {
                    return _googlechrome21calışanpencereInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("2648450c-8880-4e18-ba47-bab72973bdd0")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "2648450c-8880-4e18-ba47-bab72973bdd0", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", "?/?/list[@controlid='1']", 30000, null, "41716dcf-07eb-49ac-bad0-b569859dc699");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2648450c-8880-4e18-ba47-bab72973bdd0")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2648450c-8880-4e18-ba47-bab72973bdd0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("41716dcf-07eb-49ac-bad0-b569859dc699")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("41716dcf-07eb-49ac-bad0-b569859dc699")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

        /// <summary>
        /// The RonwellDigitalInformationTechnologyAppFolder folder.
        /// </summary>
        [RepositoryFolder("949e2635-0951-4c19-9a3c-596e38470d88")]
        public partial class RonwellDigitalInformationTechnologyAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ronwelldigitalitconsultingserviceInfo;

            /// <summary>
            /// Creates a new RonwellDigitalInformationTechnology  folder.
            /// </summary>
            public RonwellDigitalInformationTechnologyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RonwellDigitalInformationTechnology", "/dom[@domain='www.ronwelldigital.com']", parentFolder, 30000, null, false, "949e2635-0951-4c19-9a3c-596e38470d88", "")
            {
                _ronwelldigitalitconsultingserviceInfo = new RepoItemInfo(this, "RonwellDigitalITConsultingService", ".//div[#'main-wrapper']/div/div[1]/div/div/div[2]//img[@alt>'Ronwell Digital - IT Consulting']", ".//div[#'main-wrapper']//img[@alt>'Ronwell Digital - IT Consulting']", 30000, null, "bd6e7045-b2ee-4645-99e3-09cf0c4af81b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("949e2635-0951-4c19-9a3c-596e38470d88")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("949e2635-0951-4c19-9a3c-596e38470d88")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RonwellDigitalITConsultingService item.
            /// </summary>
            [RepositoryItem("bd6e7045-b2ee-4645-99e3-09cf0c4af81b")]
            public virtual Ranorex.ImgTag RonwellDigitalITConsultingService
            {
                get
                {
                    return _ronwelldigitalitconsultingserviceInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The RonwellDigitalITConsultingService item info.
            /// </summary>
            [RepositoryItemInfo("bd6e7045-b2ee-4645-99e3-09cf0c4af81b")]
            public virtual RepoItemInfo RonwellDigitalITConsultingServiceInfo
            {
                get
                {
                    return _ronwelldigitalitconsultingserviceInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("eac807dd-0d5f-455d-9390-a5c7d0b49897")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _bağlantıyıyenisekmedeacInfo;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@title='']", parentFolder, 30000, null, true, "eac807dd-0d5f-455d-9390-a5c7d0b49897", "")
            {
                _bağlantıyıyenisekmedeacInfo = new RepoItemInfo(this, "BağlantıyıYeniSekmedeAc", "container[@accessiblename='']/menubar[@accessiblename='']//menuitem[@accessiblename>'Bağlantıyı yeni sekmede a']", ".//menuitem[@accessiblename>'Bağlantıyı yeni sekmede a']", 30000, null, "b300d1cb-6452-4020-9cca-bf2d61700794");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eac807dd-0d5f-455d-9390-a5c7d0b49897")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eac807dd-0d5f-455d-9390-a5c7d0b49897")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BağlantıyıYeniSekmedeAc item.
            /// </summary>
            [RepositoryItem("b300d1cb-6452-4020-9cca-bf2d61700794")]
            public virtual Ranorex.MenuItem BağlantıyıYeniSekmedeAc
            {
                get
                {
                    return _bağlantıyıyenisekmedeacInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The BağlantıyıYeniSekmedeAc item info.
            /// </summary>
            [RepositoryItemInfo("b300d1cb-6452-4020-9cca-bf2d61700794")]
            public virtual RepoItemInfo BağlantıyıYeniSekmedeAcInfo
            {
                get
                {
                    return _bağlantıyıyenisekmedeacInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
